### ISSUE TITLE
more efficient type

### ISSUE THREAD

**Issue by stevengj** [giordano/Measurements.jl#1]
The current type `Measurement` is pretty inefficient, because it is mutable and because the fields are untyped.   You should probably do:
```jl
immutable Measurement{V<:Number,E<:Real}
    val::V
    err::E
end
```
That way you can have e.g. `Measurement{Complex{Float64},Float64}` and have it stored in memory very efficiently as 24 bytes (3 consecutive `Float64` values).

(As I understand it, since `err` is a variance, it is always real.)

**Comment by giordano** [comment]
Indeed I planned to make the type immutable, I just forgot to actually do that, but I was also thinking about leaving fields untyped, so that it can play nicely with other libraries like `SIUnits`.  I don't know 
how it could work if `val` and `err` are typed.

**Comment by stevengj** [comment]
The trick is to use a parameterized type like I showed above.   This way, you aren't defining just one type, but actually a whole family of types with different fields.

In particular, note that the `SIQuantity` type [defined by SIUnits.jl](https://github.com/Keno/SIUnits.jl/blob/d744256506bf869ca165f55555f0a21ad63052fd/src/SIUnits.jl#L10-L12) is actually a subtype of `Number`, so it will work just fine with the `Measurement` type I defined above.

Parameterized types like this are one of the key Julia techniques that enables code that is type-generic but also compact and high-performance.

**Comment by giordano** [comment]
That's interesting, but if I change the type as you suggested I cannot use a `SIQuantity` as uncertainty (`1km ± 1m`) because

``` julia
julia> SIUnits.SIQuantity <: Real
false
```

Can this be fixed somehow?

**Comment by giordano** [comment]
Maybe a new `SIUnits` type (`SIRealQuantity`?) that is subtype of `Real` and can be used to convert `SIQuantity`s to `Real`?

**Comment by stevengj** [comment]
Oh, that's a good point; I filed an issue with SIUnits, but the solution on the SIUnits end seems a bit painful.  (You're right that they could have a separate `SIRealQuantity` type, but then all of their methods will have to be updated to handle both types.)

One workaround is to have `E <: Number`, and then just check `isreal(err)` in the constructor.   This will be just as space efficient, and since `isreal(x::Real)` should be inlined as `true` at compile time, there should be little or no runtime cost.

**Comment by tlycken** [comment]
Why do you want `E <: Real` even when `!(V <: Real)`? Doesn't the notion of `val ± err` indicate that `val` and `err` must be the same type? If so, then

```
immutable Measurement{V<:Number}
    val::V
    err::V
end
```

should suffice.

**Comment by giordano** [comment]
> Why do you want `E <: Real` even when `!(V <: Real)`? Doesn't the notion of `val ± err` indicate that `val` and `err` must be the same type?

I was unsure regarding the case of complex measurements; I don't have experience with such case.  [This report](https://rf.irl.cri.nz/sites/default/files/files/Notes%20on%20complex%20measurement%20uncertainty-%20part%202.pdf) indicates that complex measurements have complex uncertainty as well, so I think your suggestion is right and I'll apply it.

> (in particular, what does `[2,3] ± 0.4` mean?)

What do you mean?  With your definition of `Measurement` type, `[2,3] ± 0.4` won't work without instructing the constructor function.

**Comment by giordano** [comment]
I made `Measurement` subtype of `Number` to make it possible to use measurements in functions taking `Number` arguments.

Is there a way to make `Measurement{T}` subtype of `T`?  This would make it possible to use `Measurement` objects in functions taking specific subtype of `Number` (like real-only or complex-only arguments).

I tried with

``` julia
immutable Measurement{T<:Number} <: T
```

but got this error:

```
ERROR: LoadError: invalid subtyping in definition of Measurement
```

**Comment by stevengj** [comment]
@giordano, no, you can't do this.  `Measurement{Float64}` *cannot* be a subtype of `Float64`, because concrete types (like `Float64`) in Julia are final (cannot have subtypes).

**Comment by stevengj** [comment]
(I was thinking of `err` as a standard deviation, and the standard deviation of complex random variable is real.    I guess you could define `real(err)` as the standard deviation of `real(val)`, and `imag(err)` as the standard deviation of `imag(val)`.)

**Comment by stevengj** [comment]
Continuing with the above comment, you should really have `+{S<:Real}{T<:Real}(a::Measurement{s}, b::Measurement{T}) = ...` and similar, leaving the `Complex` case unimplemented for now.

Or alternatively, define `Measurement` only for `T<:Real`.  That might be cleaner.

**Comment by stevengj** [comment]
The nice thing about defining `immutable Measurement{T<:Real} <: Real` is that then you can have e.g. `Complex{Measurement{Float64},Measurement{Float64}}`, attaching measurement errors to both real and imaginary parts, and (for the most part) the errors will propagate correctly.

**Comment by giordano** [comment]
> The nice thing about defining `immutable Measurement{T<:Real} <: Real` is that then you can have e.g. `Complex{Measurement{Float64},Measurement{Float64}}`, attaching measurement errors to both real and imaginary parts, and (for the most part) the errors will propagate correctly.

In the case of complex quantities, wouldn't this work only for linear functions?

**Comment by stevengj** [comment]
@giordano, no, because a lot of nonlinear functions are internally implemented in terms of elementary operations (`*`, `+`, etc.) on the real and imaginary parts, which you have already implemented in Measurements.jl.   (Look at `base/complex.jl` in the Julia source...all complex operations are implemented in Julia.)   Of course, for complicated special functions you would probably need specialized implementations in Measurements.jl

**Comment by giordano** [comment]
Regarding my question about making `Measurement{T<:Number} <: T`, I was mainly interested in the cases `T = Integer`, `T = AbstractFloat`, `T = Real`, and `T = Complex`, so with abstract type, rather than concrete ones.  Your suggestion should work with `Real` and `Complex`, but what about `Integer` and `AbstractFloat`?  I'd like to be able to run `float(Measurement(15, 2))` in order to get `Measurement(15.0, 2.0)` (probably rounding and truncation can be done on the value of the measurement only).

**Comment by stevengj** [comment]
You have to pick one abstract number type for `Measurement` to inherit from, sorry.

However, it would be pretty easy to implement `float`:
```jl
float{T<:AbstractFloat}(m::Measurement{T}) = m
float(m::Measurement) = Measurement(float(m.val), float(m.err))
```

**Comment by giordano** [comment]
Ok ok, this was easy.  What I tried before and caused me troubles was defining `convert{T<:AbstractFloat}(T, m::Measurement)` because it expects a `T` object in output (this is why I was interested in making `Measurement{T<:Number} <: T`), but I think that it's more common to call `float` rather than `convert`.  Thank you!

**Comment by giordano** [comment]
I'm more and more persuaded to change the type definition to

``` julia
immutable Measurement{T<:AbstractFloat} <: AbstractFloat
    val::T
    err::T
end
```

with the following constructor (among others):

``` julia
Measurement(val::Real, err::Real) = Measurement(promote(float(val), float(err))...)
```

Since any operation involving `Measurement` objects ends up with floating point numbers, I think there is little sense in keeping the type parametric and subtype of `Real`.  As a plus, making `Measurement` subtype of `AbstractFloat` makes it possible to use some functions for complex arguments defined only for `Complex{AbstractFloat}` (like `sqrt`, `log`, and `^`).
