### ISSUE TITLE
Constant should not be capitalized

### ISSUE THREAD

**Issue by stevengj** [giordano/Measurements.jl#2]
In Julia, `Constant(x)` would normally be understood as creating an object of type `Constant`, which is not the case here.

In this case, the function is completely redundant.  Just define:
```jl
Measurement(value::Number) = Measurement(value, zero(value))
```
and you can eliminate the `Constant` function entirely.  (Entia non multiplicanda sunt...)

**Comment by giordano** [comment]
I thought that `Constant` could have been a convenient function, with a meaningful name, to define a `Measurement` object with null uncertainty, but it's true that it's redundant.  I'm going to fix this, thank you.
